### PR TITLE
return just a boolean, not wrapped in an object

### PR DESCRIPTION
**Pull request by christianp**
I want my booleans pure and unprocessed

### CODE REVIEW

**Comment by KevinGimbel** [comment]
I thought about this PR and I don't like it. I prefer the silliness of returning an object with a "boolean" key. In my opinion it adds to the "bullshit"  and "weirdness" our projects usually have. 

I would consider adding a `/clean/` endpoint. The URL could be `/clean/true`. What do you think?

**Comment by christianp** [comment]
That's the correct answer :)

Rather than a `clean` endpoint, how about an `obscure` endpoint, which does something like return a Boolean expression which evaluates to the desired value?

**Comment by KevinGimbel** [comment]
I like where this is going :D 

But we need to either generate a lot of obscure code that could be returned or have a set of values which can be returned. 🤔

**Comment by christianp** [comment]
Here's a little page which generates random boolean expressions with the desired values: https://inquisitive-fender.glitch.me/

**Comment by christianp** [comment]
Closing this because I've just found GitHub's global pull requests page and this is listed there.

**Pull request closed without merging**
